config/routes.rb
Rails.application.routes.draw do
  resources :challenges, except: [:destroy]
  resources :attempts, except: [:destroy]
  resources :users, except: [:destroy]
  resources :relationships
  resources :user_achievements, except: [:destroy]
  resources :achievements, except: [:destroy]
  get '/', to: 'sessions#new'
  post '/', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  # delete '/logout', to: 'users#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_many :relationships
    has_many :friends, through: :relationships
    has_many :attempts
    has_many :challenges, through: :attempts
    has_many :user_achievements
    has_many :achievements, through: :user_achievements
    has_many :inverse_relationships, :class_name => "Relationship", :foreign_key => "friend_id"
    has_many :inverse_friends, :through => :inverse_relationships, :source => :user
  
  

    validates :name, presence: true
    validates :username, presence: true, uniqueness: true
    has_secure_password

    
    def accept_challenge(challenge)
        @attempt = Attempt.create(user_id: self.id, challenge_id: challenge.id, status: "Accepted")
    end

    def complete_challenge(attempt)
        @attempt = Attempt.find(attempt.id)
        @attempt.update(status: "Completed")
    end
    
    def accepted_challenges
        x = self.attempts.select {|attempt| attempt.status == "Accepted"}
        y = x.map {|a| a.challenge}
        y
    end

    def display_accepted_challenges_without_duplicates
        x = []
        self.accepted_challenges.each do |challenge|
            y = challenge.attempts.find_by(user_id: self.id)
            if y.status == "Completed"
                nil
            else
                x << y
            end
        end
        x
    end


    def completed_challenges
        x = self.attempts.select {|attempt| attempt.status == "Completed"}
        y = x.map {|a| a.challenge}
        y
    end



    def completed_achievements
        # @achievement_array = []
        if self.completed_challenges.count == 15
            user_achievement = UserAchievement.create(user_id: self.id, achievement_id: 5)
            # @achievement_array << user_achievement
        elsif
            self.completed_challenges.count == 10
            user_achievement = UserAchievement.create(user_id: self.id, achievement_id: 4)
            # @achievement_array << user_achievement
        elsif
            self.completed_challenges.count == 5
            user_achievement = UserAchievement.create(user_id: self.id, achievement_id: 3)
            # @achievement_array << user_achievement
        elsif
            self.completed_challenges.count == 1
            user_achievement = UserAchievement.create(user_id: self.id, achievement_id: 2)
            # @achievement_array << user_achievement
        else
            self
            user_achievement = UserAchievement.create(user_id: self.id, achievement_id: 1)
            # @achievement_array << user_achievement
        end
        # @achievement_array << self.achievements
        # @achievement_array.uniq
        @achievement_array = self.achievements.uniq
        @achievement_array
        
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate!, except:[:new, :create]
    
    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
    end

    def new
        @user = User.new
    end

    def create
        @user = User.create(user_params)
        if @user.save
            redirect_to '/'
        else
            render :new
        end
    end

    def edit
        @user = User.find(current_user.id)
    end

    def update
        @user = User.find(params[:id])
        @user.update(user_params)
        if @user.save
            redirect_to user_path(@user)
        else
            render :edit
        end
    end

    # def destroy
    #     @user = User.find(current_user.id)
    #     @user.destroy
    #     flash[:info] = "Your profile has been deleted"
    #     redirect_to '/'
    # end

    private 

    def user_params
        params.require(:user).permit(:name, :username, :password, :bio, :image)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%if @user.errors.present?%>
    <h2>The following errors were present that prevented this action from occurring:</h2>
    <ul>
        <%@user.errors.full_messages.each do |msg|%>
        <li style="color: red"><%=msg%></li>
        <%end%>
    </ul>
    <h2>Please make the relevant changes and try again!</h2>
<%end%>

<%=form_for @user do |f|%>
<div id="formheader">
    <%=f.label :name%>
</div>
<div id="formcontent">
    <%=f.text_field :name%>
</div>

<div id="formheader">
    <%=f.label :bio%>
</div>
<div id="formcontent">
    <%=f.text_area :bio, cols: "40", rows: "10"%>
</div>

<div id="formheader">
    <%=f.label :username%>
</div>
<div id="formcontent">
    <%=f.text_field :username%>
</div>

<div id="formheader">
    <%=f.label :password%>
</div>
<div id="formcontent">
    <%=f.password_field :password%>
</div>

<div id="formheader">
    <%=f.label "Picture"%>
</div>
<div id="formcontent">
    <%=f.text_field :image, placeholder: "Please put a URl link to your photo here"%>
</div>

<div id="formheader">
    <%=f.submit%>
</div>
<%end%>

app/views/users/edit.html.erb
<h1>Edit Your Challenge Quest Profile</h1>

<%=render("form")%>

<div id="formheader">
    <%= link_to("Your Profile", user_path(@user))%>
</div>

app/views/users/index.html.erb
<h1>List of All Active Questers</h1>


<ul>
    <%@users.each do |user|%>
            <img src="<%=user.image%>" width= "auto" height= "300px">
        <p><strong><%=link_to(user.username, user_path(user))%>
            </strong><%= button_to("Add Friend", relationships_path(:friend_id => user), :method => :post) %></p>
    <%end%>
</ul>

app/views/users/new.html.erb
<h1>Create a Challenge Quest Profile</h1>

<%=render("form")%>

app/views/users/show.html.erb
<div id="ProfilePage">
  <%=@user.name.titleize%>'s Challenge Quest Profile
</div>

<div id="edit">
    <%= button_to "Add Friend", relationships_path(:friend_id => @user), :method => :post %>
</div>

<div id="ProfilePicture">
  <img src= "<%=@user.image%>" width="auto" height="400px">
</div>

<div id="header">
  Username: 
</div>


<div id="content">
  <%=@user.username%>
</div>

<div id="header">
  Bio: 
</div>

<div id="content_bio">
  <%=@user.bio%>
</div>

<div id="header">
  Attempted Challenges: 
</div>

<div id="content_special">
<ul>
    <%@user.display_accepted_challenges_without_duplicates.each do |attempt|%>
        <p>
            <%=link_to(attempt.challenge.name, challenge_path(attempt.challenge))%><br/>(<%= link_to("Mark Challenge as Complete", attempt_path(@user.attempts.find_by(challenge_id: attempt.challenge.id)), :method => :patch) %>)
        </p>
    <%end%>
</ul>
</div>

<div id="header">
  Completed Challenges:
</div>

<div id="content_special">
  <ul>
      <%@user.completed_challenges.each do |challenge|%>
          <p>
            <%=link_to(challenge.name, challenge_path(challenge))%>
          </p>
    <%end%>
  </ul>
</div>


<div id="header">
  Completed Achievements:
</div>

<div id="content_special">
  <ul>
    <%@user.completed_achievements.each do |achievement|%>
      <p>
        <%=link_to(achievement.name, achievement_path(achievement))%>
      </p>
    <%end%>  
  </ul>
</div>


<div id="header">
  Friends of <%=@user.name.titleize%>:
</div>

<div id="content_special">
  <ul>
    <% @user.relationships.each do |relationship| %>
    <p>
      <%= link_to(relationship.friend.username, user_path(relationship.friend.id)) %>
    
      <div id="friends">
        <%= button_to "Remove Friend", relationship, :method => :delete %>
      </div>
    </p>
  <% end %>
  </ul>
</div>


<div id="header">
  Questers Who Have Befriended <%=@user.name.titleize%>:
</div>

<div id="content_special">
  <ul>
    <%@user.inverse_friends.each do |user|%>
      <p>
        <%=link_to(user.username, user_path(user))%>
      </p>
    <%end%>  
  </ul>
</div>


<div id="edit">
  <%= button_to("Edit Profile", edit_user_path, :method => :get)%>
</div>

 <%# <div id="edit">
  <%= button_to("Delete", current_user, method: :delete, data: 
  {confirm: "Are you sure you want to delete your profile?"}) %>
</div>