config/routes.rb
Rails.application.routes.draw do
  resources :challenges, except: [:destroy]
  resources :attempts, except: [:destroy]
  resources :users, except: [:destroy]
  resources :relationships
  resources :user_achievements, except: [:destroy]
  resources :achievements, except: [:destroy]
  get '/', to: 'sessions#new'
  post '/', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  # delete '/logout', to: 'users#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/challenge.rb
class Challenge < ApplicationRecord
    has_many :attempts
    has_many :users, through: :attempts

    validates :name, presence: true, uniqueness: true
    validates :description, presence: true, uniqueness: true
    
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
    before_action :authenticate!

    def index
        @challenges = Challenge.all
    end

    def show
        @challenge = Challenge.find(params[:id])
    end

    def new
        @challenge = Challenge.new
    end

    def create
        @challenge = current_user.challenges.build(challenge_params)
        if @challenge.save
            redirect_to challenge_path(@challenge)
        else
            render :new
        end
    end

    def edit
        @challenge = Challenge.find(params[:id])
        # if @challenge.users.include?(current_user)
        #     render :edit
        # else
        #     flash[:info] = "You cannot edit another user's challenge!"
        # end
        # redirect_to challenge_path(@challenge)
            
    end

    def update
        @challenge = Challenge.find(params[:id])
        @challenge.update(challenge_params)
        if @challenge.save
            redirect_to challenge_path(@challenge)
        else
            render :edit
        end
    end

    private 

    def challenge_params
        params.require(:challenge).permit(:name, :description, :category)
    end
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/challenges/_form.html.erb
<%if @challenge.errors.present?%>
    <h2>The following errors were present that prevented this action from occurring:</h2>
    <ul>
        <%@challenge.errors.full_messages.each do |msg|%>
        <li style="color: red"><%=msg%></li>
        <%end%>
    </ul>
    <h2>Please make the relevant changes and try again!</h2>
<%end%>


<%=form_for @challenge do |f|%>

<div id="formheader">
    <%=f.label :name%>
</div>
<div id="formcontent">
    <%=f.text_field :name%>
</div>

<div id="formheader">
    <%=f.label :category%>
</div>
<div id="formcontent">
    <%=f.text_field :category%>
</div>

<div id="formheader">
    <%=f.label :description%>
</div>
<div id="formcontent">
    <%=f.text_area :description, col: "40", row: "10"%>
</div>

<div id="formheader">
    <%=f.submit%>
</div>
<%end%>

app/views/challenges/edit.html.erb
<h1>Edit Your Challenge</h1>

<%=render("form")%>

<%= link_to("List of All Challenges", challenges_path)%><br/>
<%= link_to("Challenge Quest Homepage", "/")%><br/>

app/views/challenges/index.html.erb
    
    <center>
     <h1>List of All Challenges</h2>
    </center>

    
    <center>
        <div id="challenges">
        <%@challenges.each do |challenge|%>
            <p><%=link_to(challenge.name, challenge_path(challenge))%></p>
        <%end%>
        </div>
    </center>

    
<center>
    <div id="links">
        <p><%= button_to("Create a New Challenge", new_challenge_path, method: :get)%></p>
    
</div>
</center>

app/views/challenges/new.html.erb
<h1>Create a New Challenge</h1>

<%=render ("form")%>

app/views/challenges/show.html.erb
<div id="ProfilePage">
    Challenge Information
</div>

<div id="header">
    Name:
</div> 
<div id="content">
    <%=@challenge.name%>
</div>

<div id="header">
    Category:
</div>
<div id="content">
    <%=@challenge.category%>
</div>

<div id="header">
    Description:
</div>
<div id="content">
    <%=@challenge.description%>
</div>

<%= link_to("Accept Challenge", attempts_path(:challenge_id => @challenge), :method => :post) %><br/>